#!/bin/py

"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import math as m

def isTriangle(n):
	return (m.sqrt((2 * n) + 1/4) + 1/2) % 1 == 0

def isPentagonal(n):
	return (m.sqrt( 1/36 + 2*n/3) + 1/6) % 1 == 0


found = False
i = 143
while not found:
	
	i += 1
	h = i * (2 * i -1)

	if isTriangle(h) and isPentagonal(h):
		print(h)
		found = True